[package]
name = "fuel-core-compression"
version = { workspace = true }
authors = { workspace = true }
categories = ["cryptography::cryptocurrencies"]
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "cryptocurrencies", "fuel-core", "fuel-client", "fuel-compression"]
license = { workspace = true }
repository = { workspace = true }
description = "Compression and decompression of Fuel blocks for DA storage."

[dependencies]
fuel-core-types = { workspace = true, features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

postcard = { version = "1.0", features = ["use-std"] }
bincode = "1.3"

paste = "1.0"

fuel-core-compression-derive = { path = "../compression-derive" }