[package]
authors = { workspace = true }
categories = ["cryptography::cryptocurrencies"]
description = "Storage types and primitives used by Fuel core protocol."
edition = { workspace = true }
homepage = { workspace = true }
keywords = [
    "blockchain",
    "cryptocurrencies",
    "fuel-client",
    "fuel-core",
    "fuel-storage",
]
license = { workspace = true }
name = "fuel-core-storage"
repository = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
enum-iterator = { workspace = true }
fuel-core-types = { workspace = true, default-features = false, features = ["serde"] }
fuel-vm-private = { workspace = true, default-features = false }
itertools = { workspace = true }
mockall = { workspace = true, optional = true }
paste = "1"
postcard = { workspace = true, features = ["alloc"] }
primitive-types = { workspace = true, default-features = false }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[dev-dependencies]
fuel-core-types = { workspace = true, default-features = false, features = ["serde", "random", "test-helpers"] }
rand = { workspace = true }

[features]
test-helpers = ["dep:mockall"]
